### ISSUE TITLE
Setup from scratch vs create-react-app vs next.js: Which direction are we heading to?

### ISSUE THREAD

**Issue by skyshader** [twishasaraiya/GuessTheQuote#2]
So, we are planning to go with React as our front-end technology. This involves a build process to generate a code that we can serve to users.

### Build process includes:
- Webpack: Configure a build pipeline.
- Babel: Transpiling our `jsx` or `es6` code to browser supported code
- HMR (Hot Module Replacement) and development server
- A lot of dependencies in our development environment
- Managing dependencies updates
- Optimizing the build process for production (code-splitting, tree-shaking and stuff)

### Options we have:
**1. Create React App**
Create React App provides simple cli command to create application with the initial project structure, install dependencies, configure babel, webpack, HMR and package.json scripts.

_Tools it uses:_
1. Webpack
2. Babel
3. PostCSS w/ Autoprefixer
4. Jest
5. Flow (optional)

_Pros:_
1. We won't have to configure webpack or babel or hmr or any other development related packages.
2. We won't have to manage and update those packages in future, create-react-app will do that for us just by changing the version of `react-scripts`.
3. Gives us a quick jump start in order to start directly with the project specific requirements.
4. Maintained by facebook and a lot of brilliant minds in industry with tried and tested processes and configurations.
5. Doesn't require a node server. Generates static files in production which can be served from anywhere ([Now.sh](https://zeit.co/docs/examples/create-react-app), aws s3 + cloudfront / github pages / nginx configured instance).

_Cons:_
1. Limitation with changing the packages you are working with. If you want to use something that it doesn't support, you have to eject and you lose all the advantages mentioned above. But we should keep in mind, we don't always have to eject.
2. Server Side Rendering is missing.
3. Missing pre-processors for css (except basic PostCSS +2.  Autoprefixer)

Find `create-react-app` here: https://github.com/facebook/create-react-app

**2. Next.js**
A server rendered react app with minimal setup required to get started. It adds some more simplicity over what `create-react-app` already provides, without doing more.

_Tools it uses:_
1. Babel
2. Webpack
3. Styled-jsx
4. Jest

_Pros:_
1. Server side rendered apps. Read more about it [here](https://medium.com/@adamzerner/client-side-rendering-vs-server-side-rendering-a32d2cf3bfcc).
2. Pretty much configurable with most of the things (CSS Preprocessors, Flow, MobX/Redux, Apollo, etc). See the set of examples [here](https://github.com/zeit/next.js/tree/master/examples).

_Cons:_
1. React Router is not supported. But routing is still very manageable with [`next-routes`](https://github.com/fridays/next-routes)
2. State of the app is lost on route change because it renders a different page and un-mounts everything else. We use redux to handle this.

Read more about it here to know how it improves over `create-react-app` and manual build process in general: https://learnnextjs.com/basics/getting-started

**3. Custom Setup**
Here we setup the entire thing ourselves.

_Pros:_
1. Learn how the entire process works
2. Ability to manage/add/remove dependencies based on requirement

_Cons:_
1. Needs a lot of time to setup the base project.
2. Have to manage individual development and build dependencies.

### My Views
I am more oriented towards **NOT** setting up our own build process.

Why I favour `create-react-app` and `next.js` are because:
- They are npm modules, hence managed in our project as just another dependencies.
- Aren't bloated, contains only most essential functionality.
- Are properly maintained by professional community and has gone through loads of iteration to provide production ready applications and smoothen the development process.
- If later needed, can easily migrate from them.
- Save time in setup, and focus more on building rich offline experience and better user experience.

### Your Views
Please share your views on the same and based on that we can decide which direction we want to proceed. This issue will be closed once we all agree with the points and choose a particular direction.

Thanks,

**Comment by jatin11gidwani** [comment]
I would prefer using CRA because configuring the project from scratch may take a lot of time and I guess people are also not that much familiar with next.js as much with react. Also if someone wants to understand the workflow from start he/she won't need to spend much time on dependencies and all if we use CRA.

**Comment by twishasaraiya** [comment]
1. I think we should go with CRA rather than next.js as @jatin11gidwani said everyone would be more familiar with CRA rather than next.js. 
2. And also since there is a workaround to the issue of **CRA overriding our service worker**, we should go with CRA since that was the main reason for not preferring CRA(at least for me).

**Comment by danivijay** [comment]
If building from scratch can take that much time, me too supports CRA. I think @twishasaraiya can set it up, so that we can start implementing functionality asap.

Personally I feel it can be achieved easily as we got a team. That may not be the case tho.

**Comment by twishasaraiya** [comment]
I have built the client side using CRA, please feel free to make any changes if required.

**Comment by danivijay** [comment]
As we chose to move ahead with CRA, closing the issue.
